<?php

namespace App\Providers;

use App\Events\VideoCreated;
use App\Listeners\ProcessVideo;
use App\Listeners\sendEmail;
use App\Models\Like;
use App\Models\Video;
use App\Observers\LikeObserver;
use App\Observers\VideoObserver;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
      /*  Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        VideoCreated::class => [
            SendEmail::class,
            ProcessVideo::class,
        ],*/
    ];
    //کامنتشون کردم چون auto discovery فعاله , برای فعال کردنشم اون shouldDiscoverEvents()
    //در پایین صفحه رو return true کردم و توی متد handle در لیستنرها مشخص کردم که
    // به چه eventی وصل هستن

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        Like::observe(LikeObserver::class);
        Video::observe(VideoObserver::class);
    }
    public function shouldDiscoverEvents()
    {
        return true; // TODO: Change the autogenerated stub

    }

}
